import { SentimentSource, SentimentResult, Mention } from "../types";
import { generateMentionText } from "../sentiment-service";

interface TwitterMention {
  id: string;
  text: string;
  sentiment: number;
  created_at: string;
}

export const twitterSource: SentimentSource = {
  name: "Twitter",
  async fetchSentiment(location: string): Promise<SentimentResult> {
    // Generate random sentiment data
    const mentionCount = Math.floor(Math.random() * 20) + 10; // 10-30 mentions
    const mentions: Mention[] = [];
    const baseScore = Math.random() * 2 - 1; // Base sentiment between -1 and 1

    for (let i = 0; i < mentionCount; i++) {
      const sentiment = baseScore + (Math.random() * 0.6 - 0.3); // Add variation
      const daysAgo = Math.floor(Math.random() * 7); // Random date within last week
      const date = new Date();
      date.setDate(date.getDate() - daysAgo);
      
      mentions.push({
        text: generateMentionText(location, sentiment, "Twitter"),
        sentiment,
        source: "Twitter",
        date: date.toISOString(),
        url: `https://twitter.com/user/status/${Math.random().toString(36).substr(2, 9)}`,
      });
    }

    // Calculate average sentiment
    const averageSentiment = mentions.reduce((sum, m) => sum + m.sentiment, 0) / mentions.length;

    return {
      mentions,
      score: averageSentiment,
      keywords: [], // Keywords will be generated by the main service
    };
  },
};
